{% set name = "monet" %}
{% set version = "2.2.6" %}

package:
  name: monet
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/MONET/archive/v{{ version }}.tar.gz
  sha256: 826a331fc11828023e7752a232a0d9c0d7652716d41188cf93e97b49408f4194

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - xarray
    - dask
    - cartopy
    - matplotlib-base
    - seaborn
    - pyresample
    - python-stratify
    - pydecorate
    - xesmf  # [not win]
test:
  imports:
    - monet
    - monet.plots
    - monet.util

about:
  home: https://github.com/noaa-oar-arl/monet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - for meteorology and AQ
  doc_url: https://monet-arl.readthedocs.io

extra:
  recipe-maintainers:
    - zmoon
    - bbakernoaa
