{% set name = "monet" %}
{% set version = "2.3.1" %}

package:
  name: monet
  version: {{ version }}

source:
  url: https://github.com/noaa-oar-arl/MONET/archive/v{{ version }}.tar.gz
  sha256: 74d55d80887ea9f4ffcad3c585f56a6939d42957e69acbb8251623670a5a1fc0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    #
    - cartopy
    - dask
    - matplotlib-base
    - numpy
    - pandas
    - pydecorate
    - pyresample
    - python-stratify
    - seaborn
    - xarray
    - xesmf
test:
  requires:
    - python {{ python_min }}
  imports:
    - monet
    - monet.plots
    - monet.util

about:
  home: https://github.com/noaa-oar-arl/monet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - for meteorology and AQ
  doc_url: https://monet-arl.readthedocs.io

extra:
  recipe-maintainers:
    - zmoon
    - bbakernoaa
